# Docker compose file for running KrakenD API Gateway using arm64v8 architecture

services:
  krakend:
    image: devopsfaith/krakend:2.7
    ports:
      - "8080:8080"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
      - ./plugins:/etc/krakend/plugins
    environment:
      - KRAKEND_CONFIG=/etc/krakend/krakend.json